In [2]:
!java -version

java version "1.8.0_503"
Java(TM) SE Runtime Environment (build 1.8.0_503-b01)
Java HotSpot(TM) Client VM (build 25.503-b01, mixed mode, sharing)

In [3]:
import tabula

tabula.environment_info()

Python version:
    3.14.7 | packaged by conda-forge | (main, Aug 31 2026, 07:22:37) [MSC v.1944 64 bit (AMD64)]
Java version:
    java version "1.8.0_503"
Java(TM) SE Runtime Environment (build 1.8.0_503-b01)
Java HotSpot(TM) Client VM (build 25.503-b01, mixed mode, sharing)
tabula-py version: 2.10.0
platform: Windows-11-10.0.26200-SP0
uname:
    uname_result(system='Windows', node='Morgans_Desktop', release='11', version='10.0.26200', machine='AMD64')
linux_distribution: ('', '', '')
mac_ver: ('', ('', '', ''), '')

In [4]:
pdf_path = "https://github.com/chezou/tabula-py/raw/master/tests/resources/data.pdf"

dfs = tabula.read_pdf(pdf_path, stream=True)
# read_pdf returns list of DataFrames
print(len(dfs))
dfs[0]

Failed to import jpype dependencies. Fallback to subprocess.
No module named 'jpype'
'pages' argument isn't specified.Will extract only from page 1 by default.
Got stderr: Sep 01, 2026 9:12:12 PM org.apache.pdfbox.pdmodel.font.FileSystemFontProvider loadDiskCache
WARNING: New fonts found, font cache will be re-built
Sep 01, 2026 9:12:12 PM org.apache.pdfbox.pdmodel.font.FileSystemFontProvider <init>
WARNING: Building on-disk font cache, this may take a while
Sep 01, 2026 9:12:14 PM org.apache.pdfbox.pdmodel.font.FileSystemFontProvider <init>
WARNING: Finished building on-disk font cache, found 365 fonts

1

,Unnamed: 0,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2
5,Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1
6,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
7,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2
8,Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2
9,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4
10,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4
11,Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3
12,Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3
13,Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3
14,Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4
15,Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4
16,Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4
17,Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1
18,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2
19,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1
20,Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1
21,Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2
22,AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2
23,Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4
24,Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2
25,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1
26,Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2
27,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2
28,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4
29,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6
30,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8
31,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2

In [8]:
pdf_path = "C:\\Users\\willi\\Documents\\monthly_budget\\data\\raw\\tesco.pdf"

dfs = tabula.read_pdf(pdf_path, stream=True, pages=[3, 4])
# read_pdf returns list of DataFrames
print(len(dfs))
dfs[0]

2

,25 JUL,27 JUL,30022364,LYMEFIELD GARDEN CEN L HYDE ENG,Unnamed: 0,Unnamed: 1,Unnamed: 2,£8.80
0,26 JUL,27 JUL,19719802.0,WWW.BLOOMANDWILD.COM LONDON,LND,NaN,NaN,£20.54
1,26 JUL,27 JUL,10248687.0,WWW.ZIPWORLD.CO.UK LLANRWST,WLS,NaN,NaN,£15.75
2,26 JUL,27 JUL,35394067.0,NATIONAL TRUST ALTRINCHAM,NaN,NaN,NaN,£15.30
3,26 JUL,27 JUL,32921599.0,NATIONAL TRUST ALTRINCHAM,NaN,NaN,NaN,£3.00
4,26 JUL,27 JUL,9272058.0,TESCO PAY AT PUMP 4248 HATTERSLEY,NaN,NaN,NaN,£69.08
5,27 JUL,28 JUL,53756686.0,"Stables Cafe, Heaton Manchester GBR",NaN,NaN,NaN,£6.20
6,27 JUL,28 JUL,67071997.0,MANCHESTER CITY COUNCI MANCHESTER M6ENG,NaN,NaN,NaN,£2.50
7,27 JUL,28 JUL,6038591.0,TESCO GROCERY WELWYN GARDENENG,NaN,NaN,NaN,£101.84
8,28 JUL,29 JUL,21305424.0,BENTSGARDE* BENTS GARD WARRINGTON,LND,NaN,NaN,£27.35
9,28 JUL,29 JUL,26993943.0,BENTSGARDE* BENTS GARD WARRINGTON,LND,NaN,NaN,£9.95
10,28 JUL,31 JUL,4444124.0,OHSEWCRAFTY 01562747458 GBR,NaN,NaN,NaN,£22.40
11,29 JUL,30 JUL,32524325.0,AMAZON UK* WJ6973Y95 LONDON LND,NaN,NaN,NaN,£14.50
12,30 JUL,31 JUL,1447124.0,TESCO-STORES 6553 HATTERSLEY,NaN,NaN,NaN,£12.64
13,30 JUL,31 JUL,534312.0,AMAZON* CW6YE7965 LONDON LND,NaN,NaN,NaN,£6.28
14,01 AUG,03 AUG,10852460.0,TESCO-STORES 6553 HATTERSLEY,NaN,NaN,NaN,£18.35
15,02 AUG,03 AUG,30147968.0,AMAZON UK* XX9FH8DL5 LONDON LND,NaN,NaN,NaN,£30.00
16,02 AUG,03 AUG,20291755.0,LYMEFIELD GARDEN CEN L HYDE ENG,NaN,NaN,NaN,£1.90
17,02 AUG,03 AUG,48842136.0,GLOSSOP GARDEN CENTRE GLOSSOP,GBR,NaN,NaN,£13.95
18,03 AUG,04 AUG,54269801.0,SMBC PARKING ECOM STOCKPORT,NaN,NaN,NaN,£1.10
19,03 AUG,04 AUG,5027760.0,TESCO GROCERY WELWYN GARDENENG,NaN,NaN,NaN,£90.12
20,05 AUG,05 AUG,1440075.0,Northern Rail London GBR,NaN,NaN,NaN,£64.00
21,05 AUG,06 AUG,15424039.0,SAINSBURYS S/MKTS MANCHESTER 40,NaN,NaN,NaN,£5.45
22,05 AUG,06 AUG,8371030.0,NATIONAL TRUST STOCKPORT,NaN,NaN,NaN,£8.00
23,06 AUG,07 AUG,17236092.0,TESCO-STORES 6553 HATTERSLEY,NaN,NaN,NaN,£3.50
24,06 AUG,07 AUG,1353954.0,AMAZON* NC8BW1Q64 LONDON LND,NaN,NaN,NaN,£3.79
25,07 AUG,10 AUG,33826043.0,AMAZON UK* 805R71BT5 LONDON LND,NaN,NaN,NaN,£15.36
26,08 AUG,10 AUG,46694756.0,Gnosall Express Stafford GBR,NaN,NaN,NaN,£9.49
27,08 AUG,10 AUG,19453602.0,The Navigation Inn Stafford GBR,NaN,NaN,NaN,£7.65
28,08 AUG,10 AUG,9670415.0,BOAT INN STAFFORDSHIRE,NaN,NaN,NaN,£12.30
29,09 AUG,11 AUG,22099097.0,PLATINUM GNOSALL SERVI STAFFORD,GBR,NaN,NaN,£47.28
30,10 AUG,11 AUG,3609606.0,RED LION FARM HAUGHTON HAUGHTON,GBR,NaN,NaN,£7.65
31,11 AUG,12 AUG,458870.0,TESCO-STORES 6553 HATTERSLEY,NaN,NaN,NaN,£9.10
32,11 AUG,12 AUG,770612.0,TESCO GROCERY WELWYN GARDENENG,NaN,NaN,NaN,£117.22
33,12 AUG,13 AUG,24591399.0,SAINSBURYS S/MKTS MANCHESTER 40,NaN,NaN,NaN,£6.05
34,12 AUG,13 AUG,7708706.0,Tumble Jacks Stockport GBR,NaN,NaN,NaN,£23.00
35,12 AUG,13 AUG,11275205.0,Tumble Jacks Stockport GBR,NaN,NaN,NaN,£2.20
36,13 AUG,14 AUG,18197876.0,SAINSBURYS S/MKTS MANCHESTER 40,NaN,NaN,NaN,£4.90
37,13 AUG,14 AUG,65921715.0,WHITE CROSS VETS HYDE,NaN,NaN,NaN,£108.49
38,14 AUG,14 AUG,1909215.0,WP*letusplaylittletown Stalybridge GBR,NaN,NaN,NaN,£18.00
39,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2 of 3

In [20]:
import pymupdf

doc = pymupdf.open("C:\\Users\\willi\\Documents\\monthly_budget\\data\\raw\\tesco.pdf")

for i, page in enumerate(doc):
    tables = page.find_tables()
    n_tabs = 0
    for table in tables:
        n_tabs += 1
        # or get as Pandas DataFrame
        df = table.to_pandas()
        #print(df)

    print(f"Page {i+1} has {n_tabs} tables")

Page 1 has 1 tables
Page 2 has 2 tables
Page 3 has 0 tables
Page 4 has 0 tables

Use tabula, for this case appears to better extract